### ISSUE TITLE
Failed to build tauri app on win10

### ISSUE THREAD

**Issue by testforvln** [jetli/rust-yew-axum-tauri-desktop#1]
Hi, I followed the instructions and successed getting the template app run with "cargo tauri dev". 

But when I run "cargo tauri build", the generated app.exe failed to show anything with only blank window.

**Comment by bobbbay** [comment]
Looking at the source code, this seems to be the intended behaviour.

**Comment by novvoo** [comment]
http://127.0.0.1:8080  --->   https://tauri.localhost/
![4247.png](http://tva1.sinaimg.cn/large/6e557adagy1h4fpbxiye9j218k0hjacb.jpg)

**Comment by testforvln** [comment]
Thx @jingslunt !

**Comment by jetli** [comment]
should be fixed
